import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TheChakraProvider } from "../../provider/chakra.provider";
import Head from "next/head";
import { ReactNode } from "react";
import { ContactProvider } from "../../provider/contact.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Your App Title</title>
        <meta name="description" content="Your app description" />
      </Head>
      <body className={inter.className}>
        <ContactProvider>
          <TheChakraProvider>{children}</TheChakraProvider>
        </ContactProvider>
      </body>
    </html>
  );
}
